export const override = {
    Valutatore: {
        "MostraObbiettiviNonDefiniti": 0,
        "DescrizioneObiettivo": 2,
        "DescrizioneKPI": 1,
        "DataTermine": 1,
        "Peso": 2,
        "Autovalutazione": 1,
        "CommentiValutato": 1,
        "NotePersonaValutata": 1,
        "Valutazione": 3,
        "CommentiValutatore": 3,
        "NoteValutatore": 1,
        "AzioniDiSviluppoValutato": 1,
        "AzioniDiSviluppoValutatore": 3,
        "SceltaAzioniFormative": 1,
        "AutovalutazioneComplessiva": 1,
        "CommentiFinaliValutato": 1,
        "ValutazioneComplessiva": 3,
        "CommentiFinaliValutatore": 3,
        "Survey": 1,
        "ValutazioneSuggerita": -1,
        "AutovalutazioneSuggerita": 0,
        "ValutatoreAggiuntivo1": 3,
        "ValutatoreAggiuntivo2": 3,
    },
    Valutato: {
        "MostraObbiettiviNonDefiniti": 0,
        "DescrizioneObiettivo": 1,
        "DescrizioneKPI": 2,
        "DataTermine": 1,
        "Peso": 2,
        "Autovalutazione": 1,
        "CommentiValutato": 1,
        "NotePersonaValutata": 1,
        "Valutazione": 2,
        "CommentiValutatore": 2,
        "NoteValutatore": 1,
        "AzioniDiSviluppoValutato": 1,
        "AzioniDiSviluppoValutatore": 2,
        "SceltaAzioniFormative": 1,
        "AutovalutazioneComplessiva": 1,
        "CommentiFinaliValutato": 1,
        "ValutazioneComplessiva": 2,
        "CommentiFinaliValutatore": 2,
        "Survey": 1
    },
    Supervisore: {
        "DescrizioneKPI": 1,
        "ValutatoreAggiuntivo1": 2,
        "ValutatoreAggiuntivo2": 2,
        "RuoloProposto": 5,
        "CommentiRoundTable": 5,
        "AzioniDiSviluppoAggiuntive": 5
    }
}